import { Head, Link, type PageComponent } from '@ts-76/inertia-hono-jsx';
import type { GitHubActionItem } from '../../src/types';
import { Item } from './_shared';

const Design: PageComponent<'Design'> = () => {
  const sampleItem: GitHubActionItem = { id: 'design-sample', canonicalSubjectKey: 'design:sample', kind: 'authored_pr_failing', title: 'Authored PR has failing checks', repo: 'owner/repo', url: '#', updatedAt: new Date().toISOString(), reason: 'The item row, chips, title, reason, and action copy reuse the dashboard renderer.', suggestedAction: 'Fix failing checks', evidence: { checks: 'failure' }, source: 'pulls' };
  return <><Head title="Design" /><header class="masthead panel"><div><p class="eyebrow">Design language</p><h1>Interface kit</h1><p class="muted">This page is public and reuses the same components as the product UI, so changes to originals update here too.</p></div><Link class="button ghost" href="/">Back home</Link></header><section class="metrics"><Metric label="Assigned" value={3} /><Metric label="Mentioned" value={7} /><Metric label="Authored PRs" value={12} /><Metric label="Reviews" value={2} /></section><section class="section panel"><div class="section-head"><div><p class="eyebrow">Type</p><h2>Warm, crisp, operational</h2></div><span class="badge">public</span></div><p class="muted">Fraunces gives Sunrise its personality. IBM Plex Sans keeps dense dashboard text readable. IBM Plex Mono marks system labels, chips, code, and table headers.</p><p class="actions"><a class="button primary" href="#">Primary action</a><button class="button ghost">Secondary action</button><button class="button quiet">Quiet action</button></p></section><section class="section panel"><div class="section-head"><div><p class="eyebrow">Action item</p><h2>Dashboard row</h2></div><span class="badge">example</span></div><div class="item-list"><Item item={sampleItem} /></div></section><section class="section panel"><div class="section-head"><div><p class="eyebrow">Setup pattern</p><h2>First-boot cards</h2></div></div><div class="deploy-card"><div><strong>Start with one-click deploy</strong><p>Cards, copy, buttons, and code styling mirror onboarding.</p></div><a class="button primary" href="#">Deploy to Cloudflare</a></div><div class="config-card"><p><span>Homepage URL</span><code>https://sunrise.example.workers.dev</code></p><p><span>Callback URL</span><code>https://sunrise.example.workers.dev/callback</code></p></div></section><section class="section panel"><div class="section-head"><div><p class="eyebrow">Table</p><h2>Runs table</h2></div></div><table><thead><tr><th>Started</th><th>Trigger</th><th>Status</th><th>Candidates</th></tr></thead><tbody><tr><td>2026-05-01</td><td>manual</td><td><span class="badge">succeeded</span></td><td>18</td></tr></tbody></table></section></>;
};

function Metric({ label, value }: { label: string; value: number }) { return <div class="metric panel"><span>{label}</span><strong>{value}</strong></div>; }

export default Design;
