export const SUNRISE_VERSION = {
  name: 'sunrise',
  version: '0.2.0',
  commit: 'local',
  upstream: 'https://github.com/adewale/sunrise',
  changelog: 'CHANGELOG.md',
  upgradeContract: 'docs/agent-upgrade-contract.md',
  verify: 'npm run verify',
  deploy: 'npx wrangler deploy',
  privacy: 'No phone-home or deployment registry is required for update visibility. Deployer-owned agents pull public upstream code.',
} as const;

export const SUNRISE_CHANGELOG = `# Changelog

All notable Sunrise changes are recorded here for deployers and their coding agents.

## [0.2.0] - 2026-05-28

### User-facing changes

- Switched the dashboard to true client-side navigation via Inertia. Links between Dashboard, Settings, Item, Changelog, and Runs no longer trigger a full document reload; the theme toggle and other chrome state survive.
- Hydrated the Manual refresh, Save settings, and other forms so the submit button shows an in-flight state without a page reload.
- Set a per-page document title (Dashboard, Settings, Runs, ...) via the Inertia head manager.

### Operational changes

- Moved the client/server build onto Vite with \`@cloudflare/vite-plugin\`. The deployed worker now serves hashed assets from a real production build.
- Adopted \`@hono/inertia\` on the server and \`@ts-76/inertia-hono-jsx\` on the client. The SSR root document and the client entry both go through \`createInertiaApp\`.
- Migrated the full test suite into \`@cloudflare/vitest-pool-workers\` so SSR, routes, scanner, queue, and refresh tests run against real D1 inside real workerd.
- Added a browser end-to-end suite that drives a real \`vite preview\` worker via Playwright, including a click-through SPA-nav assertion.

### Agent upgrade notes

- The build now requires \`npx vite build\` before \`wrangler deploy\`. The \`deploy\` npm script chains them.
- Per-page prop shapes are exported from \`src/app.tsx\` and mapped to Inertia page names in \`app/page-props.ts\`. Pages are typed as \`PageComponent<'Name'>\`.
- \`app/pages.gen.ts\` is auto-generated by \`@hono/inertia/vite\`; do not edit it.

## [0.1.0] - 2026-05-03

### User-facing changes

- Added a GitHub inbox/dashboard for self-hosted Cloudflare deployments.
- Added setup diagnostics, OAuth troubleshooting, operations runs, settings, pagination, and design pages.
- Added calendar-style inbox sections, direct GitHub unresolved links, card-level pages, and GitHub repo links.
- Added watched-repository notification filtering. Subscribed/watched repo notifications are off by default.
- Added scheduled refreshes every four hours, anchored around 06:00 in the deployment cron timezone.

### Operational changes

- Added D1 migrations and indexes for inbox queries.
- Added queue-backed GitHub change processing, DLQs, refresh summaries, reconciliation, and ETag-based no-change detection.
- Added screenshot capture and release scripts.

### Agent upgrade notes

- Follow \`docs/agent-upgrade-contract.md\`.
- Preserve deployer-specific \`wrangler.jsonc\` resource IDs, D1 database names, queue names, secrets, and OAuth configuration.
- Verify with \`npm run verify\`.
- Apply D1 migrations before deploy when new migration files are present.
`;
